model: gc_vit_xxtiny
epochs: 310
warmup_epochs: 20
cooldown_epochs: 10
batch_size: 128
#opt: local
#lr: 0.005
#weight_decay: 2e-2
lr_ep: False
lr_cycle_decay: 1.0
lr_cycle_limit: 1
lr_cycle_mul: 1.0
min_lr: 5e-7
warmup_lr: 1e-6
amp: True
sched: cosine
crop_pct: 0.875
aa: none
mixup: 0.0
cutmix: 0.0
clip_grad: 5.0
clip_mode: norm
color_jitter: 0.4
model_ema: False
model_ema_decay: 0.9998
model_ema_force_cpu: False
